import type {Metadata} from "next";
import {Geist, Geist_Mono, Parkinsans} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/UI/NavBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const parkinSans = Parkinsans({
    variable: "--font-parkinsans",
    subsets: ["latin"]
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" >
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${parkinSans.variable} antialiased`} >
                <NavBar />
                <main >
                    {children}
                </main >
            </body >
        </html >
    );
}
