import "@radix-ui/themes/styles.css";
import "./globals.css";
import './theme-config.css';

import { NavBar } from "@/components/UI";
import { Container, Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Parkinsans } from "next/font/google";
import AuthProvider from "./auth/Provider";
import ReactQueryClientProvider from '@/components/QueryClientProvider'
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const parkinSans = Parkinsans({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-parkinsans",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={parkinSans.variable} >
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${parkinSans.variable} antialiased`} >
                <ReactQueryClientProvider>
                    <AuthProvider>
                        <Theme accentColor="violet" grayColor="olive" radius="large">
                            <NavBar />
                            <main className={`px-5`}>
                                <Container>
                                    {children}
                                </Container>
                            </main >
                        </Theme>
                    </AuthProvider>
                </ReactQueryClientProvider>
            </body >
        </html >
    );
}
